spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost/pickandpop
      username: pickandpop
      password: pickandpop
      data:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.HSQLDialect
  profiles:
    active: test
    include: swagger
logging:
  level:
    root: warn
    org.springframework: info
    javax.persistence: info    
server:
  port: 8080